### ISSUE TITLE
File format of collapsed BED files and localcov

### ISSUE THREAD

**Issue by YolandiSwart** [nicolerg/gtex-admixture-la#5]
Hi, 

I'm currently conducting eQTL mapping in a five-way admixed population. However, I'm using the latest version of RFMix, thus the .msp.tsv files and viterbri files look different than whilst using the previous version of RFMix with pophased mode. 

I would like to know how the ancestry.chr${i}.bed" files and chr${i}".hg19.maf0.localcov.tsv.gz files must look like in the last step of generating the collapsed BED files in interpolate-local-anc.py ?  

Thank you.

**Comment by nicolerg** [comment]
Hi @YolandiSwart, sorry I did not see this until now. Here are samples of these file formats in case it is useful to anyone else. 

`ancestry.chr${i}.bed`:
```
#chrom: chromosome 
#start: bp start
#end: bp end 
#ancestry: ancestry abbreviation, e.g., ASN (Asian), AFR (African), EUR (European), UNK (unknown)
#subject_haplotype: format [SUBJID]_A or [SUBJID]_B for haplotype A and B, respectively

#chrom	start	end	ancestry	subject_haplotype
chr1	10539	17676348	AFR	GTEX-1117F_A
chr1	17676418	18607827	EUR	GTEX-1117F_A
chr1	18607992	156612157	AFR	GTEX-1117F_A
chr1	156784689	165131479	EUR	GTEX-1117F_A
chr1	165270034	187015947	AFR	GTEX-1117F_A
```

`chr${i}.hg19.maf0.localcov.tsv.gz`:
```
#SUBJID: subject ID
#SNP_ID: variant/SNP ID
#POS: SNP position on the chromosome given by the file name 
#AFR: number of African alleles
#ASN: number of Asian alleles
#EUR: number of European alleles
#UNK: number of alleles of indeterminate ancestry 

SUBJID	SNP_ID	POS	AFR	ASN	EUR	UNK
GTEX-11DYG	chr1_17559_G_C_b38	17559	1	0	0	1
GTEX-11NV4	chr1_17559_G_C_b38	17559	0	0	0	2
GTEX-ZLWG	chr1_17559_G_C_b38	17559	1	0	0	1
GTEX-12126	chr1_17559_G_C_b38	17559	1	0	0	1
GTEX-VJYA	chr1_17559_G_C_b38	17559	1	0	0	1
```
